//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RedmondTradeDBEntities : DbContext
    {
        public RedmondTradeDBEntities()
            : base("name=RedmondTradeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblAboutUs> TblAboutUs { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
        public virtual DbSet<TblMainPage> TblMainPage { get; set; }
        public virtual DbSet<TblMessage> TblMessage { get; set; }
        public virtual DbSet<TblService> TblService { get; set; }
        public virtual DbSet<TblSolution_Partners> TblSolution_Partners { get; set; }
        public virtual DbSet<TblWork> TblWork { get; set; }
        public virtual DbSet<TblConteiner> TblConteiner { get; set; }
    }
}
