//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConsignee
    {
        public int ID { get; set; }
        public string CCompanyName { get; set; }
        public string CAdress { get; set; }
        public string CTelefon { get; set; }
        public string CEmail { get; set; }
        public string CTaxOfficeNumber { get; set; }
    }
}
