//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConteiner
    {
        public int ID { get; set; }
        public string Short_Content { get; set; }
        public string ContainerNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Deportune_Port { get; set; }
        public string Kim { get; set; }
        public string Product { get; set; }
        public Nullable<int> Pcs { get; set; }
        public string BuyerCompany { get; set; }
        public string Nots { get; set; }
    }
}
