//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGtip
    {
        public int ID { get; set; }
        public string Mal_Hizmet { get; set; }
        public string Miktar { get; set; }
        public string BirimF { get; set; }
        public string MalHizTut { get; set; }
        public string Gtip { get; set; }
        public string StokKod { get; set; }
    }
}
