//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMainPage
    {
        public int ID { get; set; }
        public string Photo1 { get; set; }
        public Nullable<int> Solution_Partners { get; set; }
        public string Photo2 { get; set; }
        public Nullable<int> Work { get; set; }
        public Nullable<int> About_Us { get; set; }
        public string Photo3 { get; set; }
        public string İmage2 { get; set; }
        public string image3 { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual TblAboutUs TblAboutUs { get; set; }
        public virtual TblSolution_Partners TblSolution_Partners { get; set; }
        public virtual TblWork TblWork { get; set; }
    }
}
