//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tblortakproforma
    {
        public int ID { get; set; }
        public string InvoiceNo { get; set; }
        public string BookingNo { get; set; }
        public string ContainerNo { get; set; }
        public string CCompanyName { get; set; }
        public string CAdress { get; set; }
        public string CTelefon { get; set; }
        public string CEmail { get; set; }
        public string CTaxOfficeNumber { get; set; }
        public string SCompanyName { get; set; }
        public string SAdress { get; set; }
        public string STelefon { get; set; }
        public string SEmail { get; set; }
        public string STaxOfficeNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> Quantity1 { get; set; }
        public string Quantity2 { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Container { get; set; }
        public Nullable<double> WeightKG { get; set; }
        public Nullable<double> NetWeightKG { get; set; }
        public string HSCode { get; set; }
    }
}
