//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblShipper
    {
        public int ID { get; set; }
        public string SCompanyName { get; set; }
        public string SAdress { get; set; }
        public string STelefon { get; set; }
        public string SEmail { get; set; }
        public string STaxOfficeNumber { get; set; }
    }
}
