//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTax
    {
        public int ID { get; set; }
        public string ContName { get; set; }
        public string DesProd { get; set; }
        public string Quantity { get; set; }
        public string GtipHis { get; set; }
        public string DD { get; set; }
        public string ContNo { get; set; }
        public string HC { get; set; }
        public string INVOICENO { get; set; }
        public string SGSNO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Vaelur { get; set; }
        public string Droist { get; set; }
        public string TotalDroist { get; set; }
        public string BizimBeyan { get; set; }
        public string Montant { get; set; }
        public string SG { get; set; }
        public string Import { get; set; }
    }
}
