//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedmondTradeWork.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrun
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Quantity2 { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Container { get; set; }
        public Nullable<double> Weight_KG { get; set; }
        public Nullable<int> HSCode { get; set; }
    }
}
